### ISSUE TITLE
Use "$id" as property name for schema URI (instead of "id")

### ISSUE THREAD

**Issue by Photosynthesis** [MurmurationsNetwork/MurmurationsLibrary#33]
Schemas currently in the library have an "id" property that contains the canonical URI for the schema. For example `"id": "https://cdn.murmurations.network/schemas/murmurations_map-v1.json"`. According to the JSON-Schema spec, the [name of this property should be "$id"](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.8.2.1). Unless there is a reason to keep "id" as the property name, we could update to use "$id" in existing and future schemas, per the specification.

**Comment by geoffturk** [comment]
@Photosynthesis The renaming from `id` to `$id` did not take place until Draft 6: https://datatracker.ietf.org/doc/html/draft-wright-json-schema-01#appendix-B (linked from: https://json-schema.org/specification-links.html#draft-6)

We've been aiming for compatibility with Draft 4, mainly because of the first schema parsing library we used. I think RJSF works with Draft 7 and up, so maybe we want to bump up to a higher version?

**Comment by Photosynthesis** [comment]
Oh! Thanks for the background on this @geoffturk. Makes sense. 

You are more familiar with the implications of various drafts, so I am happy to follow your judgement about whether or when to update. I like the idea of going to a higher version while we still have only a handful of schemas and a relatively modest amount of code that would need to be updated, if there aren't known compatibility issues with the change.

**Comment by Photosynthesis** [comment]
I'll close this issue, and we can open a new issue on the topic of a JSON-Schema version update.
